name: Check Deno type

on:
  push:

jobs:
  check:
    name: Check type
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup deno
        uses: denoland/setup-deno@v1
      - name: check fmt
        run: deno fmt --check
      - name: type check
        run: deno check *.ts
      - name: linting
        run: deno lint *.ts
